services:
  next:
    build:
      context: .
      dockerfile: ./infra/next/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./front:/app
    environment:
      # hot reloadを有効にするためらしい
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    networks:
      - common
    ports:
      - "3000:3000"
      - "6006:6006" # storybook
    container_name: next
  playwright:
    build:
      context: .
      dockerfile: ./infra/playwright/Dockerfile
    tty: true
    ipc: host # メモリ不足エラー対策
    volumes:
      - ./playwright:/playwright
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /playwright
    environment:
      DISPLAY: :0
    command: sh -c "npm install"
    container_name: playwright
    depends_on:
      - next
    network_mode: "host"
    env_file:
      - ./playwright/.env # 環境変数を読み込む
    # networks:
    #   - common
    # extra_hosts:
    #   - "localhost:backend"  # localhostをbackendコンテナにマッピング
networks:
  common:
    driver: bridge # ネットワークモードをbridgeに設定
